development:
  adapter: postgresql
  encoding: unicode
  database: bx_pokecoin_dev
  pool: 5
  host: localhost
  port: 5432
  username: bx_pokecoin
  password: '1234'

staging:
  url: <%= ENV['DATABASE_URL'] %>

production:
  url: <%= ENV['DATABASE_URL'] %> 
